# Generated by Django 3.1.5 on 2021-06-13 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Index', '0002_auto_20210612_0629'),
    ]

    operations = [
        migrations.CreateModel(
            name='client_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('links', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='client_images/')),
            ],
        ),
    ]
